# Generated by Django 2.1.3 on 2018-11-08 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[(A-Z)|(a-z)|(\\s)|(\\-)]+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[(A-Z)|(a-z)|(\\s)|(\\-)]+$')])),
                ('permanent_address', models.CharField(max_length=75, validators=[django.core.validators.RegexValidator('^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\-)|(\\.)|(,)|(\\:)]+$')])),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\s*(?:\\+?(\\d{1,3}))?([-. (]*(\\d{3})[-. )]*)?((\\d{3})[-. ]*(\\d{2,4})(?:[-.x ]*(\\d+))?)\\s*$', message='Please enter a valid phone number')])),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('links', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^(https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]\\.[^\\s]{2,})+$')])),
                ('about', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\.)|(,)|(\\-)|(!)]+$')])),
                ('area_of_expertise', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Front End Development'), (2, 'Back End Development'), (3, 'Full Stack Developer'), (4, 'Machine Learning'), (5, 'Data Science'), (6, 'Block Chain Developer'), (7, 'Android/ios Developer'), (8, 'Graphic Designer'), (9, 'Competitive Programmer'), (10, 'Embeded System/IOT'), (11, 'Cloud and Networking')], max_length=23)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('current_city', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='cities_light.City')),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='cities_light.Country')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='cities_light.Region')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
