# Generated by Django 2.1.3 on 2018-11-09 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20181109_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='area_of_expertise',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\.)|(,)|(\\-)|(!)]+$')]),
        ),
    ]
