# Generated by Django 2.1.3 on 2018-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20181109_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
