# Generated by Django 2.1.3 on 2018-11-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_auto_20181109_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static_cdn/media_root/default_profile_pic.png', upload_to='alumni'),
        ),
    ]
