# Generated by Django 2.1.3 on 2018-11-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_auto_20181109_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static_cdn/static_root/default_profile_pic.png', upload_to='alumni'),
        ),
    ]
