# Generated by Django 2.1.3 on 2018-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20181112_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, default='alumni/default_profile_pic.png', upload_to='alumni'),
        ),
    ]
